### ISSUE TITLE
Many to Many associations in my route and model discussion

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-4-issues#1]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I cant figure out how to make n to n associations / model needs another lookover

### Post any code you think might be relevant (one fenced block per file)
```
router.patch('/:apartmentId/tags', requireToken, (req, res, next) => {
    delete req.body.tag.owner

    Tag.findById(req.params.id)
    .then(handle404)
    .then((tag) => {
        requireOwnership(req, tag)
        return tag.updateOne(req.body.tag)
    })
    .then(() => res.sendStatus(204))
    .catch(next)

```
### What is your best guess as to the source of the problem?
Not sure. Its structured to create tag and apartment separately at the moment then the association happens

### What things have you already tried to solve the problem?
Apartment.findByIdAndUpdate(apartmentId, {
```
//         $push: {
//             tags: tag._id
//         }}, 
//         {
//             new: true,
//             useFindAndModify: false
//         }
        
//     )
```

**Comment by tkolsrud** [comment]
Are you having trouble creating the apartments and tags simultaneously, or accessing the data afterwards?

**Comment by isaac8069** [comment]
apartments and tags are created. how to associate? I could have done a findOrCreate tag and associated to the apartment as well. Wasn't sure the best approach

**Comment by isaac8069** [comment]
This was the findOrCreate route...i made some changes but more or less this was it
```
  req.body.tag.apartments.push(req.params.apartmentId)
	Tag.findOrCreate(req.body.tag)
		// respond to succesful `create` with status 201 and JSON of new "tag"
		.then((tag) => {
            console.log('THIS IS FOUND TAG', tag)
            apartment.findById(req.params.apartmentId)
                .then(foundApartment => {
                    foundApartment.tags.push(tag._id)
                    foundApartment.save()
                    res.status(201).json({ tag: tag.toObject() })
                })
		})
		.catch(next)
```

**Comment by tkolsrud** [comment]
Ah, yeah i mean that looks right to me. The only association you need is the reference Id for tag being stored somewhere in the apartment object. Have you had a chance to test it?

**Comment by TaylorDarneille** [comment]
https://forum.freecodecamp.org/t/pushing-mongoose-documents-to-another-document-as-array-elements/400067

User = apartment
Bundle = tag

**Comment by isaac8069** [comment]
![Screen Shot 2022-01-10 at 1 01 39 PM](https://user-images.githubusercontent.com/90520586/148815733-51716381-3d9c-4884-ae39-5bd67e804a01.png)
This is the code for this route:
```
// POST /apartmentId/tags
router.post('/add-tag/:id', requireToken, (req, res, next) => {
    const apartmentTag = (req.body.tag)
    apartment.findById({ _id: req.params.id })
    .exec()
        .then(handle404)
        .then(apartment => {
            // requireOwnership(req, tag)
            const tag = new Tag({
                apartmentTag
            })
            tag.save()
                .then(tag => {
                    console.log('THSI IS THE TAGid', tag._id)
                    apartment.tags.push(tag._id)
                    apartment.save()
                        .then((apartment) => res.status(200).json(apartment))
                        .catch(next)
                })
        })
})
```

**Comment by isaac8069** [comment]
![Screen Shot 2022-01-10 at 1 46 12 PM](https://user-images.githubusercontent.com/90520586/148821586-e39cd1c8-9b8f-43d4-800f-8c16f3cdd930.png)
**Updated error message**

**Comment by isaac8069** [comment]
```
// UPDATE
// POST /add-tag/apartmentId
router.post('/add-tag/:id', requireToken, (req, res, next) => {
    const apartmentTag = (req.body.tag)
    apartment.findById({ _id: req.params.id })
    .exec()
        .then(handle404)
        .then(apartment => {
            const tag = new Tag({
                apartmentTag
            })
            tag.save()
            .then(tag => {
                // requireOwnership(req, tag)
                console.log('THSI IS THE TAGid', tag._id)
                    apartment.tags.push(tag._id)
                    apartment.save()
                        .then((apartment) => res.status(200).json(apartment))
                        .catch(err => res.status(400).json('Error on tag save: ' + err))
                })
        })
        .catch(next)
})
```

**Comment by TaylorDarneille** [comment]
push the tag, not the id

**Comment by TaylorDarneille** [comment]
Gonna close this. First write a post route for apartments, and a post route for tags, before working on associating them :)
