### ISSUE TITLE
Empty posts on MongoDB

### ISSUE THREAD

**Issue by DG-98** [WDI-SEA/project-4-issues#10]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN 
### What's the problem you're trying to solve?
When using a post route in postman, the db entry ends up being empty for some reason 

### Post any code you think might be relevant (one fenced block per file)
```router.post("/list", (req, res, next) => {
  // set owner of new example to be current user
  // req.body.Video.owner = req.user.id
  List.create(req.body)
    // respond to succesful `create` with status 201 and JSON of new "example"
    .then((createdList) => {
      res.status(201).json({ createdList: createdList.toObject() })
    })
    // if an error occurs, pass it off to our error handler
    // the error handler needs the error message and the `res` object so that it
    // can send an error message back to the client
    .catch(next)
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
no error message just posts with no body

### What is your best guess as to the source of the problem?
Honestly not sure, I've tried checking spelling and syntax but it made no difference 

### What things have you already tried to solve the problem?

**Comment by tkolsrud** [comment]
try console logging req.body to see if anything's hitting the server

**Comment by DG-98** [comment]
this is what's returned 
![image](https://user-images.githubusercontent.com/85405879/148820920-84c7ecf3-b8c4-475b-88f4-d335bbb2ffda.png)

**Comment by tkolsrud** [comment]
and nothing shows up in your database?

**Comment by DG-98** [comment]
This is what the entries look like 
![image](https://user-images.githubusercontent.com/85405879/148832731-82549a6f-546d-4ba1-9302-4f607c367867.png)

**Comment by tkolsrud** [comment]
It seems like since the req.body is already an object you're taking some extra steps?

**Comment by DG-98** [comment]
I cut back on some stuff so it posts like this: 
![image](https://user-images.githubusercontent.com/85405879/148834037-574ab845-3f61-4f1b-a5c9-2eeb983164a1.png)
but it still shows up in the DB like the other pic I sent

**Comment by tkolsrud** [comment]
what's your schema look like?

**Comment by DG-98** [comment]
```const mongoose = require("mongoose")


const listSchema = new mongoose.Schema(
    {
        animeId: {
            type: Number,
            require: true,
        },
        title: {
            type: String,
            require: true,
        }
    }
)

const List = mongoose.model("List", listSchema)

module.exports = List

**Comment by tkolsrud** [comment]
So i think that's your issue. AnimeID and title are nested inside of "List", and aren't getting assigned to their respective keys in the schema
