### ISSUE TITLE
Model issues

### ISSUE THREAD

**Issue by jyang1003** [WDI-SEA/project-4-issues#12]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN
### What's the problem you're trying to solve?
Invalid schema configuration: `Model` is not a valid type at path `nutrition`

### Post any code you think might be relevant (one fenced block per file)
```
const mongoose = require('mongoose')
const Nutrition = require('./nutrition')

const User = require('./user')

const profileSchema = new mongoose.Schema({
    name: {
        type: String,
        required: false
    },
    height: {
        type: Number,
        required: false
    },
    weight: {
        type: Number,
        required: false
    },
    age: {
        type: Number,
        required: false
    },
    baseCaloricMaintenence: {
        type: Number,
        required: false
    },
    caloricGoal: {
        type: Number,
        required: false
    },
    proteinGoal: {
        type: Number,
        required: false
    },
    carbsGoal: {
        type: Number,
        required: false
    },
    fatsGoal: {
        type: Number,
        required: false
    },
    nutrition: Nutrition,
    owner: {
        // this links the user Id
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    }
})

module.exports = mongoose.model('Profile', profileSchema)

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

<img width="1192" alt="Screen Shot 2022-01-10 at 1 39 30 PM" src="https://user-images.githubusercontent.com/91720534/148820703-98a183f5-c2ea-4dc6-8509-392d10aa89de.png">
### What is your best guess as to the source of the problem?
Either something wrong with one of my schemas or routes

### What things have you already tried to solve the problem?
google, but most of the issues other people had are typos and i can't find any

**Comment by DoireannJane** [comment]
The nutrition is linking to another schema right?

**Comment by jyang1003** [comment]
Nutrition is a subdoc of profile

**Comment by DoireannJane** [comment]
Right but the owner of it links to user right?

**Comment by jyang1003** [comment]
Yeah it should

**Comment by jyang1003** [comment]
Fixed! Thanks Dori.
