### ISSUE TITLE
Need to discuss sockets vs DMs vs masking an email

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-4-issues#13]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN
### What's the problem you're trying to solve?
I tried implementing sockets, but I don't think I want to go down that path. I do not want a chat. I either want to mask an email address attached to an apartment listing or direct messaging within the app. 

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
N/A

### What is your best guess as to the source of the problem?

time constraint
### What things have you already tried to solve the problem?
I tried sockets io, but seems like a lot of work that I may not have time for figuring out. I installed it on both server and client. I wrote some code on both client and server too. I am rethinking and planning how I want users to contact each other.

**Comment by isaac8069** [comment]
<img width="434" alt="Screen Shot 2022-01-10 at 1 57 50 PM" src="https://user-images.githubusercontent.com/90520586/148823228-e37cf4dd-6952-4e30-b018-dd6b1b6f0492.png">
**This is what i mean by masking**
I can email the below address and it will be sent to the apartment owner. The actual email address is alexandra.hungerbuhler@gmail.com

**Comment by timmshinbone** [comment]
The way craigslist does this is by something called 'piping'. Basically, that fake email addy you see there is a unique identifier that lives alongside the real email address, the message goes through to the fake one, checks to see if it matches any real emails, and sends the message to the real email address when it finds a match. The only thing I've been able to find are PHP scripts that do this, but there HAS to be a node or javascript package that does something similar. I'm still trying to find them, one possible thing that might be neat to look into and may be able to help you get past this, is the package [mailparser](https://www.npmjs.com/package/mailparser)

**Comment by isaac8069** [comment]
Thanks Timm! I will make that my deliverable for tonight
