### ISSUE TITLE
Passing Data from React to Django

### ISSUE THREAD

**Issue by hectorzaragoza** [WDI-SEA/project-4-issues#23]
### What stack are you using? 
Django - React

### What's the problem you're trying to solve?
I am trying to pass a state from React to Django API to create a conditional statement in the backend based on what the user selects on the front end.

### Post any code you think might be relevant (one fenced block per file)

Front End Code
![image](https://user-images.githubusercontent.com/62188104/149006602-c14fde72-b170-41a9-9c0f-afa0b9b5b96d.png)

Back End Code
![image](https://user-images.githubusercontent.com/62188104/149006724-fa35379e-8b69-4dff-9773-36a72404f5f0.png)

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
My QueryDict is empty.

### What is your best guess as to the source of the problem?
I am not passing form data correctly.

### What things have you already tried to solve the problem?
Tried different parsers from Django and different form inputs.

**Comment by timmshinbone** [comment]
Were those supposed to be screenshots? I can't see the images.

**Comment by hectorzaragoza** [comment]
> Were those supposed to be screenshots? I can't see the images.

I just edited it - they should be viewable now.

**Comment by hectorzaragoza** [comment]
We solved this issue by creating an axios call to carry a payload from FE to BE. However, adding the onSubmit functionality to do the axios call and removing the form action that triggered the STRIPE API checkout session, resulted in the data being transferred but a failed connection to Stripe. So, I ended up including both an onSubmit for Axios and an Action for the routing to Stripe.
