### ISSUE TITLE
Just makin sure

### ISSUE THREAD

**Issue by Mackmiller** [WDI-SEA/project-4-issues#25]
### What stack are you using? 
DR

### What's the problem you're trying to solve?

I just want to double check that it's fine that the only way my migration would go through was because I imported the specific model into my __ init __.py file? I had briefly come across this problem in one of the class labs last week, which is how I knew to try it for P4. Before I did this, the migration was just never going through and I never got any error messages.

**Comment by timmshinbone** [comment]
Should be alright, we'll see once we get to deployment if that's the case though lol (should be fine, but we can find a workaround if not)

**Comment by Mackmiller** [comment]
Got it- I'll keep it in mind for deployment later
