### ISSUE TITLE
Connecting DB to React

### ISSUE THREAD

**Issue by jmeier2715** [WDI-SEA/project-4-issues#27]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
PERN
### What's the problem you're trying to solve?
Having issues connecting frontend to the backend. Not even receiving a post request upon signing up a user 

### Post any code you think might be relevant (one fenced block per file)
```
```

### What is your best guess as to the source of the problem?
I think there is more refactoring for the routes before they are properly connected

### What things have you already tried to solve the problem?

**Comment by TaylorDarneille** [comment]
Do you need more help on this? I vaguely remember Doireann going in to talk to you but didn't hear the result.

**Comment by jmeier2715** [comment]
I'm moving on to other parts for the sake of time but I'll open another one tomorrow when I circle back to it
