### ISSUE TITLE
Can't get images from API to show up on page

### ISSUE THREAD

**Issue by emilybarwinczak** [WDI-SEA/project-4-issues#28]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
get the images from the API to render on the page, posting for poor sweet Ana who has been frustrated for hours

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
a bunch but it doesn't know one of the attributes/properties of the API, keeps returning as null

### What is your best guess as to the source of the problem?
API roadgoat aint the goat like we thought

### What things have you already tried to solve the problem?
feels like everything, a ton of people have tried to help

**Comment by timmshinbone** [comment]
Did you still need help on this? (if not add the solution here and close the issue)

**Comment by emilybarwinczak** [comment]
Tom is in here with us now trying to help, been stuck since lunch yesterday

**Comment by emilybarwinczak** [comment]
actually Tom said yes please

**Comment by anaismveras** [comment]
I still cant figure this out its frustrating!
