### ISSUE TITLE
post routes aren't working for both tags and apartments

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-4-issues#29]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN
### What's the problem you're trying to solve?
requireToken is having to be removed throughout my routes  and I am running into a server error

### Post any code you think might be relevant (one fenced block per file)
```
import { useEffect, useState } from 'react'
import apiUrl from '../../../apiConfig'

const CreateTag = (props) => {
    const [newTag, setNewTag] = useState({
        name: '',
    })

    const handleChange = (e) => {
        setNewTag({ ...newTag, [e.target.name]: e.target.value })
    }

    // const handleCheck = (e) => {
    //     setNewTag({ ...newTag, [e.target.name]: e.target.checked })
    // }

    const postTag = (e) => {
        e.preventDefault()
        let preJSONBody = {
            name: newTag.name
        }
        fetch(`${apiUrl}/tags`, {
            method: 'POST',
            body: JSON.stringify(preJSONBody),
            headers: { 'Content-Type': 'application/json' }
        })
            .then(response => response.json())
            .then(postedTag => {
                console.log('POSTED TAG', postedTag)
                // props.refreshTags()
                setNewTag({
                    name: ''
                })
            })
            .catch(err => console.error(err))
    }

    return (
        <form onSubmit={postTag}>
            <div>
                <label htmlFor="name">Name:</label>
                <input type="text" name="name" id="name" onChange={handleChange} value={newTag.name} />
            </div>

            <input type="submit" value="Post" />
        </form>
    )
}

export default CreateTag
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
500 (Internal Server error)

### What is your best guess as to the source of the problem?
The 500 Internal Server error could be caused by an error during the execution of any policy within Edge or by an error on the target/backend server. The HTTP status code 500 is a generic error response. It means that the server encountered an unexpected condition that prevented it from fulfilling the request.

### What things have you already tried to solve the problem?
Restarting the server/client in terminal, restructuring my code numerous times, and using other examples to help fix the post routes
<img width="1425" alt="Screen Shot 2022-01-12 at 12 00 27 AM" src="https://user-images.githubusercontent.com/90520586/149066950-cf4daa25-57da-49f1-80bd-a2c981477042.png">
.

**Comment by isaac8069** [comment]
<img width="1440" alt="Screen Shot 2022-01-12 at 12 05 16 AM" src="https://user-images.githubusercontent.com/90520586/149067173-b3a21c21-6a63-4751-ba27-4b02a292345b.png">

**Comment by isaac8069** [comment]
![Screen Shot 2022-01-12 at 10 26 06 AM](https://user-images.githubusercontent.com/90520586/149169763-8ff218c4-8ca5-4f95-8fa0-88af3f83a76a.png)

**Comment by DoireannJane** [comment]
First maybe clear your chrome data just to make sure it's not a browser issue? Then we can look at those lines that are flagged as well as the type error.

**Comment by isaac8069** [comment]
Its cleared

**Comment by isaac8069** [comment]
Resolved!
