### ISSUE TITLE
Auth does not work, any workaround?

### ISSUE THREAD

**Issue by jyang1003** [WDI-SEA/project-4-issues#3]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN
### What's the problem you're trying to solve?
Bcrypt does not work on my laptop

### Post any code you think might be relevant (one fenced block per file)
```

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
<img width="1440" alt="Screen Shot 2022-01-10 at 9 09 39 AM" src="https://user-images.githubusercontent.com/91720534/148779560-818de90e-34b1-413c-b8d1-b688f6c748b8.png">
<img width="1440" alt="Screen Shot 2022-01-10 at 9 09 52 AM" src="https://user-images.githubusercontent.com/91720534/148779579-c06ae6b0-4193-4401-9bd7-fe1a03475131.png">

### What is your best guess as to the source of the problem?
No clue

### What things have you already tried to solve the problem?
Timm told me to look up alternatives but everything said bcryptjs which also does not work. Simplecrypt was also recommended but I tried installing that and it did not work.

**Comment by tkolsrud** [comment]
So jerry, you're going to leave hashing as a stretch goal for after you've reached all other mvp right?

**Comment by jyang1003** [comment]
Yeah, hashing will be a stretch goal and I'll continue to search for alternatives for bcrypt and bcryptjs.
