### ISSUE TITLE
Cloudinary API implementation on server/ And talk through where i am in my P4/ and understanding of some key components

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-4-issues#32]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN
### What's the problem you're trying to solve?
Need clarity on the best approach for cloudinary implementation
### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
N/A

### What is your best guess as to the source of the problem?
Not sure if i should do another .then with in the post route for the apartment or if it needs to be a separate post route. I would like for image upload to happen at apartment creation

### What things have you already tried to solve the problem?
Looking at cloudinary documentation and my old code from P2

**Comment by tkolsrud** [comment]
Wait, so what is the end goal you're trying to achieve?

**Comment by isaac8069** [comment]
I want to create an apartment listing with an uploaded image using cloudinary api
