### ISSUE TITLE
Form Submission Grabbing a value

### ISSUE THREAD

**Issue by harrdev** [WDI-SEA/project-4-issues#33]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN
### What's the problem you're trying to solve?
Trying to capture input value and set state key with it

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?
Anonymous onChange function to setState with it.

**Comment by DoireannJane** [comment]
Could you include a screenshot of what you've tried?

**Comment by harrdev** [comment]
I have tried a few different ways.  Code is evolving.

**Comment by DoireannJane** [comment]
![Screen Shot 2022-01-12 at 11 48 23 AM](https://user-images.githubusercontent.com/63173333/149184564-ff5c1752-a392-40c3-ba39-74759855a9b5.png)
