### ISSUE TITLE
Discuss Model Setup and CRUD requirements

### ISSUE THREAD

**Issue by hectorzaragoza** [WDI-SEA/project-4-issues#4]
### What stack are you using? 
Django + React

### What's the problem you're trying to solve?
My website CRUD is taken care of through the Admin Portal so I don't have a need to create all of those views since a regular user should not be able to CRUD a 'service' that they are purchasing. Is that acceptable?

Also, the preexisting user model is replacing two of my proposed models so now I only have two models instead of 3.

**Comment by timmshinbone** [comment]
Let's chat about this soon, I'll need to see what you mean live, I'll slack ya when I'm ready

**Comment by hectorzaragoza** [comment]
Resolved issue with Timm.

Given the nature of my app and the CRUD options available through the Django Admin Portal, I will not be needing full CRUD routes in the services views. Superusers will use the Admin Portal to CRUD services while regular users (users interested in purchasing services) will only be able to view services available and services owned by them (via protected Detail path). Regular users will be able to update (add to) their services by purchasing additional services.
