### ISSUE TITLE
Need help with date filtering logic

### ISSUE THREAD

**Issue by jyang1003** [WDI-SEA/project-4-issues#46]
### What's the problem you're trying to solve?
Can't figure out logic to filter a day by the specific week in the calendar

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?
so i figured out I can use modulus to figure out the actual day(sunday, monday, etc...) but I can't figure out how to figure out if its the same week/different week so that I'm not displaying the data for every single monday or sunday on my bar graph. I thought about using moment.js and their built in `inBetween()`  or their built in `isAfter()` and `isBefore()` functions however that doesn't prevent spillage into the next/previous week

**Comment by DoireannJane** [comment]
Could you show me exactly what you've tried?
