### ISSUE TITLE
git push not working since last night

### ISSUE THREAD

**Issue by shuzel99** [WDI-SEA/project-4-issues#48]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN
### What's the problem you're trying to solve?
git push origin main 

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Error cannot spawn sh: no such file or directory
fatal: could not read username for 'https://github.com' : No such file or directory"

### What is your best guess as to the source of the problem?
google tells me it has something to do with a large amount of tags
### What things have you already tried to solve the problem?
On a google deep dive about ssh keys. Figuring it out but any help is appreciated

**Comment by tkolsrud** [comment]
Resolved, but keeping an eye out
