### ISSUE TITLE
Need to ask questions and talk through REACT concepts

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-4-issues#50]
### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?

**Comment by TaylorDarneille** [comment]
Please articulate a question here.

**Comment by TaylorDarneille** [comment]
If you're still struggling with tags (sounded like you were last night) I suggest you revert to the approved proposal ERD (which intentionally EXcluded U or D-ing tags).

**Comment by TaylorDarneille** [comment]
Happy to clarify questions about that though, just need a ballpark for what your questions are.

**Comment by isaac8069** [comment]
Currently trying to understand how to pass props into other components to have them render so I can delete or edit. I used the react dev tools and see them pulling in as virtual DOM, but I believe what comes next is being lost on me. Also, could you clarify "EXcluded U or D-ing tags"?

**Comment by TaylorDarneille** [comment]
Ok that's great! You're passing the props appropriately it sounds like. Are you able to see those values showing on the page or are you unsure how to display those values?

Ah sorry, I meant to only plan on being able to create and read tags, not update or delete them.

**Comment by isaac8069** [comment]
Oh okay. Well no need to continue with this ticket as I am able to create and read tags. And to answer your question. I can not see them pulling into my EditTag component. I assume I need to map through them in the return. But as stated above no need to edit or delete. So I will move on. Thanks!
