### ISSUE TITLE
running server issue

### ISSUE THREAD

**Issue by emilybarwinczak** [WDI-SEA/project-4-issues#8]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Ana and I have the same code and I'm getting this weird error and they're not, hmmm.....

### Post any code you think might be relevant (one fenced block per file)
![image](https://user-images.githubusercontent.com/92114356/148796652-5624e531-8a98-453e-b9b9-b75c932c2cc6.png)

### What is your best guess as to the source of the problem?
not sure, we have the same code and mine isn't working

### What things have you already tried to solve the problem?
googling and looking into node_module files

**Comment by tkolsrud** [comment]
I'll come take a look at that. Def don't touch anything inside node_modules!

**Comment by emilybarwinczak** [comment]
thanks tom!  ran the following: 

rm -rf node_modules
npm update
